using System;
using System.Collections.Generic;
using System.IO;
using System.Text.RegularExpressions;

namespace SkillWeightMod
{
    /// <summary>
    /// The broad/narrow category membership for every skill, loaded from skill-categories.json.
    ///
    /// That file is generated by tools/taxonomy.py, which is also what produces skill-tags.md.
    /// Keeping the rules in one place means the weighting and the documentation can never
    /// disagree; the alternative was reimplementing ~40 classification rules in C#.
    ///
    /// The parser is hand-rolled against the exact shape taxonomy.py emits rather than pulling
    /// in a JSON library, since the plugin has no dependencies of its own.
    /// </summary>
    internal static class CategoryData
    {
        public static readonly List<string> BroadCategories = new List<string>();
        public static readonly List<string> NarrowCategories = new List<string>();

        private static readonly Dictionary<string, string[]> BroadBySkill =
            new Dictionary<string, string[]>(StringComparer.Ordinal);
        private static readonly Dictionary<string, string[]> NarrowBySkill =
            new Dictionary<string, string[]>(StringComparer.Ordinal);

        private static readonly string[] None = new string[0];

        private static readonly Dictionary<string, int> Sizes =
            new Dictionary<string, int>(StringComparer.Ordinal);

        public static bool Loaded { get; private set; }
        public static int SkillCount { get; private set; }

        /// <summary>How many skills carry this category. 0 if unknown.</summary>
        public static int SizeOf(string category)
        {
            return Sizes.TryGetValue(category, out int n) ? n : 0;
        }

        /// <summary>
        /// Inverse-frequency baseline: skillCount / how many skills carry the category.
        /// A category on 5 skills is a far sharper signal than one on 225, so this makes the
        /// shipped default mean "equal pull per unit of rarity" rather than "equal pull".
        /// </summary>
        public static float BaselineWeight(string category)
        {
            if (SkillCount > 0 && Sizes.TryGetValue(category, out int size) && size > 0)
                return (float)Math.Round((double)SkillCount / size, 2);
            return 1f;
        }

        public static string[] BroadOf(string skillName)
        {
            if (skillName != null && BroadBySkill.TryGetValue(skillName, out string[] v))
                return v;
            return None;
        }

        public static string[] NarrowOf(string skillName)
        {
            if (skillName != null && NarrowBySkill.TryGetValue(skillName, out string[] v))
                return v;
            return None;
        }

        public static void Load()
        {
            Loaded = false;
            BroadCategories.Clear();
            NarrowCategories.Clear();
            BroadBySkill.Clear();
            NarrowBySkill.Clear();
            Sizes.Clear();

            try
            {
                string path = Path.Combine(
                    Path.GetDirectoryName(typeof(CategoryData).Assembly.Location) ?? ".",
                    "skill-categories.json");

                if (!File.Exists(path))
                {
                    Plugin.Log.LogWarning(
                        "skill-categories.json not found next to the plugin. Broad and narrow " +
                        "affinity will contribute nothing; tree affinity and the dependency " +
                        "bonus still work.");
                    return;
                }

                Parse(File.ReadAllText(path));
                Loaded = true;

                Plugin.Log.LogInfo(
                    $"Loaded categories for {SkillCount} skills " +
                    $"({BroadCategories.Count} broad, {NarrowCategories.Count} narrow).");
            }
            catch (Exception e)
            {
                Plugin.Log.LogError($"Could not read skill-categories.json: {e.Message}");
            }
        }

        private static void Parse(string json)
        {
            ReadNameList(json, "broadCategories", BroadCategories);
            ReadNameList(json, "narrowCategories", NarrowCategories);
            ReadCounts(json, "broadCounts");
            ReadCounts(json, "narrowCounts");

            Match total = Regex.Match(json, @"""skillCount""\s*:\s*(\d+)");
            if (total.Success)
                SkillCount = int.Parse(total.Groups[1].Value);

            // Each skill object is emitted by taxonomy.py with "name" first and the two
            // category arrays last, so a non-greedy sweep per object is enough.
            var skill = new Regex(
                "\"name\"\\s*:\\s*\"(?<name>(?:[^\"\\\\]|\\\\.)*)\".*?" +
                "\"broad\"\\s*:\\s*\\[(?<broad>[^\\]]*)\\].*?" +
                "\"narrow\"\\s*:\\s*\\[(?<narrow>[^\\]]*)\\]",
                RegexOptions.Singleline);

            int count = 0;
            foreach (Match m in skill.Matches(json))
            {
                string name = Unescape(m.Groups["name"].Value);
                if (string.IsNullOrEmpty(name))
                    continue;

                BroadBySkill[name] = SplitStrings(m.Groups["broad"].Value);
                NarrowBySkill[name] = SplitStrings(m.Groups["narrow"].Value);
                count++;
            }

            if (SkillCount == 0) SkillCount = count;
        }

        private static void ReadCounts(string json, string key)
        {
            Match block = Regex.Match(json, @"""" + Regex.Escape(key) + @"""\s*:\s*\{([^}]*)\}",
                                      RegexOptions.Singleline);
            if (!block.Success)
                return;

            foreach (Match m in Regex.Matches(block.Groups[1].Value,
                                              @"""((?:[^""\\]|\\.)*)""\s*:\s*(\d+)"))
            {
                Sizes[Unescape(m.Groups[1].Value)] = int.Parse(m.Groups[2].Value);
            }
        }

        private static void ReadNameList(string json, string key, List<string> into)
        {
            Match m = Regex.Match(json, "\"" + key + "\"\\s*:\\s*\\[([^\\]]*)\\]", RegexOptions.Singleline);
            if (m.Success)
                into.AddRange(SplitStrings(m.Groups[1].Value));
        }

        private static string[] SplitStrings(string arrayBody)
        {
            var values = new List<string>();
            foreach (Match m in Regex.Matches(arrayBody, "\"((?:[^\"\\\\]|\\\\.)*)\""))
                values.Add(Unescape(m.Groups[1].Value));
            return values.ToArray();
        }

        private static string Unescape(string s)
        {
            return s.Replace("\\\"", "\"").Replace("\\\\", "\\")
                    .Replace("\\n", "\n").Replace("\\r", "\r").Replace("\\t", "\t");
        }
    }
}
